# Generated by Django 2.2.3 on 2019-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190706_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Genderqueer/Non-Binary')], max_length=1, null=True),
        ),
    ]
