# Generated by Django 2.2.3 on 2019-07-04 18:15

import ckeditor.fields
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20190702_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-pk',), 'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='coordinate',
            field=location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Story caption'),
        ),
    ]
