# Generated by Django 2.2.3 on 2019-07-09 09:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20190705_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='geocoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
