# Generated by Django 2.2.3 on 2019-07-09 12:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20190709_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='geocoding',
        ),
        migrations.AddField(
            model_name='story',
            name='geocoding',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
