# Generated by Django 2.2.3 on 2019-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20190709_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='geocoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
