# Generated by Django 2.2.3 on 2019-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20190716_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='city_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
