# Generated by Django 2.2.3 on 2019-07-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20190718_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
    ]
