# Generated by Django 2.2.3 on 2019-07-22 14:58

from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_remove_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=stdimage.models.StdImageField(default='images/default.jpg', upload_to=dynamic_filenames.FilePattern(filename_pattern='images/{app_label:.25}/{uuid:base32}{ext}')),
            preserve_default=False,
        ),
    ]
